---
version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
  groups:
    python-packages:
      patterns:
      - "*"
  ignore:
  # ansible-core depends on resolvelib<1.1.0 and >=0.5.3
  - dependency-name: "resolvelib"
