---
role_name_check: 1

driver:
  name: docker

platforms:
  - name: "clickhouse-${DISTRO_NAME:-debian}-${DISTRO_VER:-10}-${CLICKHOUSE_VER:-latest}-${CI_JOB_ID:-0}"
    image: "${DISTRO_NAME:-debian}:${DISTRO_VER:-10}"
    dockerfile: ../resources/Dockerfile.j2
    cgroupns_mode: host
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
    capabilities:
      - 'CAP_NET_ADMIN'
      - 'CAP_IPC_LOCK'
      - 'CAP_SYS_NICE'
      - 'CAP_NET_BIND_SERVICE'
    tmpfs:
      - /run
      - /run/lock
      - /sys/fs/cgroup/systemd
      - /tmp
    # https://www.freedesktop.org/software/systemd/man/latest/systemd.html#SIGRTMIN+3
    stop_signal: 'SIGRTMIN+3'
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

provisioner:
  name: ansible
  env:
    CLICKHOUSE_VER: ${CLICKHOUSE_VER:-'*'}
    CLICKHOUSE_SETUP: ${CLICKHOUSE_SETUP:-'full'}
  inventory:
    links:
      group_vars: ./inventory/group_vars/

scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    # cover ansible --check as well
    - check
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
